<?php
// This file is part of Moodle - http://moodle.org/.
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * English language strings for block_aipromptgen.
 *
 * @package    block_aipromptgen
 * @category   string
 * @copyright  2025 AI4Teachers
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

$string['aipromptgen:addinstance'] = 'Add a new AI Prompt Generator block';
$string['aipromptgen:manage'] = 'Use the AI Prompt Generator block in a course';
$string['aipromptgen:myaddinstance'] = 'Add the AI Prompt Generator block to the Dashboard';
$string['classtype:assessment'] = 'Assessment/Test';
$string['classtype:discussion'] = 'Discussion';
$string['classtype:groupwork'] = 'Group work';
$string['classtype:lab'] = 'Lab/Practical';
$string['classtype:lecture'] = 'Lecture';
$string['classtype:project'] = 'Project-based';
$string['classtype:review'] = 'Review/Revision';
$string['form:agerangelabel'] = 'Student age/grade';
$string['form:audience'] = 'Audience (teacher-facing or student-facing)';
$string['form:audiencebrowse'] = 'Browse audiences';
$string['form:backtocourse'] = 'Back to course';
$string['form:class_typelabel'] = 'Class type';
$string['form:classtypebrowse'] = 'Browse class types';
$string['form:copied'] = 'Copied!';
$string['form:copy'] = 'Copy to clipboard';
$string['form:course'] = 'Course';
$string['form:custom_prompt'] = 'Custom Prompt';
$string['form:download'] = 'Download .txt';
$string['form:includeimages'] = 'Include images generated by DALL-E';
$string['form:language'] = 'Prompt language';
$string['form:languagebrowse'] = 'Browse languages';
$string['form:lessonbrowse'] = 'Browse…';
$string['form:lessoncount'] = 'Number of classes';
$string['form:lessonduration'] = 'Lesson duration (minutes)';
$string['form:lessonlabel'] = 'Lesson title';
$string['form:outcomesbrowse'] = 'Browse competencies/outcomes';
$string['form:outcomeslabel'] = 'Outcomes / objectives';
$string['form:provider'] = 'Provider';
$string['form:purpose'] = 'Prompt purpose (e.g., lesson plan, quiz, rubric)';
$string['form:reset'] = 'Clear saved prompt';
$string['form:response'] = 'AI response';
$string['form:result'] = 'Generated AI prompt';
$string['form:sendtoai'] = 'Send to AI';
$string['form:sendtochatgpt'] = 'Send to ChatGPT';
$string['form:subjectlabel'] = 'Subject';
$string['form:submit'] = 'Generate prompt';
$string['form:templates_hint'] = 'Predefined templates — fields are optional.';
$string['form:templates_label'] = 'Quick Templates';
$string['form:topicbrowse'] = 'Browse course sections';
$string['form:topiclabel'] = 'Teaching topic (area)';
$string['help:agerange'] = 'Type an age or grade, or click Browse to pick exact age or range';
$string['help:audience'] = 'Type an audience or click Browse to pick';
$string['help:classtype'] = 'Type a class type or click Browse to pick from a list';
$string['help:language'] = 'Type a language or click Browse to pick from installed languages';
$string['help:lesson'] = 'Type a lesson title or click Browse to pick a section/activity';
$string['help:lessonbrowse'] = 'Browse sections and activities';
$string['help:outcomes'] = 'List outcomes/objectives (one or more)';
$string['help:outcomesbrowse'] = 'Browse competencies/outcomes';
$string['help:purpose'] = 'Type a purpose or click Browse to pick from a list';
$string['help:subjectchange'] = 'Change the subject name if necessary';
$string['help:topic'] = 'Type a topic or click Browse to pick from course sections';
$string['label:agerange'] = 'Student age/grade';
$string['label:audience'] = 'Audience';
$string['label:classtype'] = 'Class type';
$string['label:language'] = 'Language';
$string['label:lesson'] = 'Lesson title';
$string['label:lessoncount'] = 'Number of classes';
$string['label:lessonduration'] = 'Lesson duration';
$string['label:outcomes'] = 'Outcomes';
$string['label:purpose'] = 'Purpose';
$string['label:subject'] = 'Subject';
$string['label:topic'] = 'Teaching topic (area)';
$string['lang:en'] = 'English';
$string['lang:pt'] = 'Portuguese';
$string['lang:sk'] = 'Slovak';
$string['lang:sr'] = 'Serbian';
$string['lang:sr_cr'] = 'Serbian (Cyrillic)';
$string['notallowed'] = 'This tool is only available to teachers and managers in this course.';
$string['openpromptbuilder'] = 'Open AI Prompt Builder';
$string['option:lessonplan'] = 'Lesson plan';
$string['option:quiz'] = 'Quiz questions';
$string['option:rubric'] = 'Assessment rubric';
$string['option:student'] = 'Student-facing';
$string['option:teacher'] = 'Teacher-facing';
$string['option:worksheet'] = 'Worksheet / activities';
$string['placeholder:agerange'] = 'e.g., 15 or 10–12';
$string['pluginname'] = 'AI tools for teachers - prompt generator';
$string['privacy:metadata'] = 'The AI Prompt Generator block does not store personal data.';
$string['prompt:instructions'] = 'Generate the output fully in the specified language. Ensure that the content is appropriate for the given student age/grade, matches the local curriculum when applicable, and directly supports the stated objectives. Structure the output clearly, using headings, subheadings, and bullet points where appropriate.';
$string['prompt:prefix'] = 'You are an expert instructional designer helping a teacher in the Moodle course {$a->course}.';
$string['setting:apikey'] = 'OpenAI API key';
$string['setting:apikey_desc'] = 'API key for OpenAI. Stored in Moodle configuration.';
$string['setting:claude_apikey'] = 'Claude API key';
$string['setting:claude_apikey_desc'] = 'API key for Anthropic Claude. Stored in Moodle configuration.';
$string['setting:claude_model'] = 'Claude model';
$string['setting:claude_model_desc'] = 'Model to use when sending the prompt to Claude (e.g. claude-3-5-sonnet-latest).';
$string['setting:custom_apikey'] = 'Custom API key (optional)';
$string['setting:custom_apikey_desc'] = 'API key for the custom endpoint. Leave empty if not required.';
$string['setting:custom_endpoint'] = 'Custom API endpoint';
$string['setting:custom_endpoint_desc'] = 'Full URL of a custom OpenAI-compatible endpoint (e.g. http://localhost:1234/v1/chat/completions).';
$string['setting:custom_model'] = 'Custom API model';
$string['setting:custom_model_desc'] = 'Model name to send to the custom endpoint.';
$string['setting:deepseek_apikey'] = 'DeepSeek API key';
$string['setting:deepseek_apikey_desc'] = 'API key for DeepSeek. Obtain from https://platform.deepseek.com/';
$string['setting:deepseek_model'] = 'DeepSeek model';
$string['setting:deepseek_model_desc'] = 'Model to use for DeepSeek (e.g. deepseek-chat, deepseek-reasoner).';
$string['setting:gemini_apikey'] = 'Gemini API key';
$string['setting:gemini_apikey_desc'] = 'API key for Google Gemini. Stored in Moodle configuration.';
$string['setting:gemini_model'] = 'Gemini model';
$string['setting:gemini_model_desc'] = 'Model to use when sending the prompt to Gemini (e.g. gemini-1.5-flash).';
$string['setting:max_tokens'] = 'Max tokens';
$string['setting:max_tokens_desc'] = 'Maximum number of tokens (words/characters) in the AI response. Default: 1024. Higher values allow longer responses but cost more. Note: for Gemini this controls maxOutputTokens; for Ollama it controls num_predict.';
$string['setting:model'] = 'OpenAI model';
$string['setting:model_desc'] = 'Chat completion model to use when sending the prompt to ChatGPT.';
$string['setting:ollama_endpoint'] = 'Ollama endpoint';
$string['setting:ollama_endpoint_desc'] = 'Base URL of the local Ollama server (e.g. http://localhost:11434).';
$string['setting:ollama_model'] = 'Ollama model';
$string['setting:ollama_model_desc'] = 'Local model name loaded in Ollama (e.g. llama3, llama3.2, mistral, codellama, phi3:mini).';
$string['setting:ollama_num_predict'] = 'Ollama max tokens (num_predict)';
$string['setting:ollama_num_predict_desc'] = 'Maximum tokens to generate (num_predict option). Lower for faster responses.';
$string['setting:ollama_schema'] = 'Ollama structured output schema';
$string['setting:ollama_schema_desc'] = 'Optional JSON Schema to constrain Ollama responses (leave empty for free-form text).';
$string['setting:ollama_timeout'] = 'Ollama request timeout (seconds)';
$string['setting:ollama_timeout_desc'] = 'Maximum time to wait for Ollama response. Increase for large outputs.';
$string['setting:rate_limit'] = 'Rate limit (per hour)';
$string['setting:rate_limit_desc'] = 'Number of AI requests allowed per user per hour. Set to 0 to disable limiting. Default: 50.';
$string['setting:system_prompt'] = 'System prompt';
$string['setting:system_prompt_desc'] = 'Custom instruction sent to the AI before every request (applies to all providers). Leave empty to use the built-in default: "You are a helpful assistant." Increase for large outputs.';
$string['setting:temperature'] = 'Temperature';
$string['setting:temperature_desc'] = 'Controls randomness of AI responses (0.0 = deterministic, 2.0 = very creative). Default: 0.7.';
$string['setting:templates'] = 'Predefined templates (JSON)';
$string['setting:templates_desc'] = 'A JSON array of templates. Each template should be an object with "title" and "prompt". If empty, built-in defaults are used.<br><br><b>Available placeholders:</b> {subject}, {topic}, {lesson}, {audience}, {outcomes}, {style}, {purpose}, {language}.<br><br><b>Example 1 (Simple):</b><br><pre>[
  {
    "title": "Glossary",
    "prompt": "Create a list of 10 key terms for {subject}, topic: {topic}. Audience: {audience}."
  }
]</pre><br><b>Example 2 (Complex with newlines):</b><br><pre>[
  {
    "title": "Detailed Lesson Plan",
    "prompt": "Write a 5E lesson plan for {subject}.\n\nTopic: {topic}\nOutcomes: {outcomes}"
  }
]</pre>';
$string['status_connecting'] = 'Connecting...';
$string['status_done'] = 'Done';
$string['status_error'] = 'Error';
$string['status_error_occurred'] = 'Error occurred';
$string['status_finished'] = 'Finished';
$string['status_receiving'] = 'Receiving...';
$string['status_started'] = 'Started';
$string['status_streaming'] = 'Streaming...';
$string['status_timeout'] = 'Timeout (incomplete)';
$string['system_role'] = 'You are a helpful assistant.';
$string['tooltip:editprompt'] = 'Edit the generated prompt before sending';
$string['tooltip:provider_not_configured'] = 'No AI provider is configured.';
$string['view:html'] = 'HTML';
$string['view:htmlcode'] = 'HTML CODE';
$string['view:raw'] = 'RAW';
$string['view:text'] = 'TEXT';
